### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Gobot1234** [Gobot1234/steam-ext-tf2#1]
- [x] Set up protobufs and base framework.
- [x] SO messages.
- [x] Examples, README and setup.py.
- [ ] Fix heartbeat pings to not constantly disconnect and reconnect.
- [x] Add currencies module.
